# -*- coding: utf-8 -*-
"""Week 2(Sat)HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dx9tF9cwnXypZgsSmJCCvOZQ2ejomY4y

# Boston Housing Price Prediction using Regression

This project explores regression models for predicting housing prices
using the Boston Housing dataset.

The project includes:
- Exploratory Data Analysis (EDA)
- Data Preprocessing
- Model Training
- Model Evaluation

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

"""**DataSet Selection**"""

url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)
df.head()

"""Basic Dataset Information"""

print("Dataset Shape:", df.shape)
print("Columns:", df.columns)
print("Dataset Info:")
print(df.info())
print("Data Type:", df.dtypes)
print("Missing Values:")
print(df.isnull().sum())
print("Summary Statistics:")
print(df.describe())
print("Missing Values:")
print(df.isnull().sum())

"""**Exploratory Data Analysis(EDA)**"""

df.describe()

"""Distribution of House Prices"""

plt.figure(figsize=(8,5))

plt.hist(df['medv'], bins=30)

plt.title('Distribution of House Prices')
plt.xlabel('Median Value (MEDV)')
plt.ylabel('Frequency')

plt.show()

"""Rooms vs House Prices"""

plt.figure(figsize=(8,5))

plt.scatter(df['rm'], df['medv'])

plt.title('Rooms vs House Prices')
plt.xlabel('Rooms (RM)')
plt.ylabel('House price (MEDV)')

plt.show()

"""Lower Status Population vs House Prices"""

plt.figure(figsize=(8,5))

plt.scatter(df['lstat'], df['medv'])

plt.title('Lower Status Population vs House Prices')
plt.xlabel('Lower Status Population (%)')
plt.ylabel('House price (MEDV)')

plt.show()

"""Correlation Matrix"""

correlation=df.corr()
print(correlation)

"""Data Preprocessing
Define Features and Target Variable
"""

X = df.drop("medv", axis=1)
y = df["medv"]

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

"""Train Regression Model

Random Forest Regression
"""

from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    max_depth=None
)
model.fit(X_train,y_train)

"""Make Predictions"""

y_pred = model.predict(X_test)

print("Predicted Values:")
print(y_pred[:5])

"""Model Evaluation

Mean Absolute Error (MAE)
"""

mae = mean_absolute_error(y_test, y_pred)

print("Mean Absolute Error:", mae)

"""Root Mean Squared Error (RMSE)"""

rmse = np.sqrt(mae)

print("Root Mean Squared Error:", rmse)

"""R² Score"""

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

"""Actual vs Predicted Values Visualization"""

plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')

plt.title('Actual vs Predicted House Prices')

plt.show()

"""## Conclusion

In this project:

- Exploratory Data Analysis (EDA) was performed
- Data preprocessing techniques were applied
- Random Forest Regression model was trained
- Model performance was evaluated using:
  - MAE
  - MSE
  - RMSE
  - R² Score

The model successfully predicted house prices with good accuracy.
"""